

DROP TABLE IF EXISTS recommendations CASCADE;
DROP TABLE IF EXISTS routine_exercises CASCADE;
DROP TABLE IF EXISTS routines CASCADE;
DROP TABLE IF EXISTS exercises CASCADE;

DROP TABLE IF EXISTS assignments CASCADE;

DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS employees CASCADE;

DROP TABLE IF EXISTS employee_types CASCADE;
DROP TABLE IF EXISTS contract_types CASCADE;

DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS programs CASCADE;
DROP TABLE IF EXISTS areas CASCADE;
DROP TABLE IF EXISTS faculties CASCADE;

DROP TABLE IF EXISTS campuses CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
